### ISSUE TITLE
how to add in NaviTabs it is not working ...

### ISSUE THREAD

**Issue by mailtokarthik2003** [igor-baiborodine/vaadin-demo-business-app#29]
NaviTabs
Tabs that when clicked navigate to a specific target (view) and that can be closed. 

How to add in this Mainlayout.????

**Comment by igor-baiborodine** [comment]
I don't maintain the source code in this project. The source code is generated quarterly using Vaadin's Starter. You'd better address this issue with the Vaadin team.

**Comment by mailtokarthik2003** [comment]
i don't want the full source code i need how to add NaviTabs in mainlayout??????

**Comment by igor-baiborodine** [comment]
Sorry, can't help you with that.
